---
# Using Ansible, configure three VLANs on the Arista switch specifying both the VLAN IDs and the VLAN names.  
#For the VLAN IDs randomly pick three numbers between 100 and 999.

- name: Class 4 Ansible Exercise1
  hosts: arista
  tasks:
    - name: green VLANs
      eos_vlan: name=GREEN vlanid=420
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}
    - name: blue VLANs
      eos_vlan: name=BLUE vlanid=430
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}
    - name: red VLANs
      eos_vlan: name=RED vlanid=440
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}