---
# Use Ansible to configure your 'primary Ethernet interface' as follows
#interface description:     *** IN USE ***
#switchport mode:          access
#VLAN:                           <one of the VLANs created in exercise1>
# primary interface == Ethernet4
# secondary interface == Ethernet3

- name: Class 4 Ansible Exercise1
  hosts: arista
  tasks:
    - name: Change description of Ethernet4
      eos_interface: name=Ethernet4 description="**IN USE**"
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}
    - name: blue VLANs
      eos_switchport: name=Ethernet4 mode=access access_vlan=430 trunk_allowed_vlans=all
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}
