---
# Use Ansible to configure your 'primary Ethernet interface' as follows
#interface description:     *** IN USE ***
#switchport mode:          access
#VLAN:                           <one of the VLANs created in exercise1>
# primary interface == Ethernet4
# secondary interface == Ethernet3

- name: Class 4 Ansible Exercise1
  hosts: arista
  tasks:
    - name: Reset Ethernet4 back to default
      eos_switchport: name=Ethernet4 mode=access access_vlan=430 trunk_allowed_vlans=all
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    - name: Reset Ethernet4 Description
      eos_interface: name=Ethernet4 admin=enable null_as_default=true
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    - name: Reset green VLANs
      eos_vlan: name=GREEN vlanid=420 state=unconfigured
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    - name: Reset blue VLANs
      eos_vlan: name=BLUE vlanid=430 state=unconfigured
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    - name: Reset red VLANs
      eos_vlan: name=RED vlanid=440 state=unconfigured
            eapi_username={{ eapi_username}}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}
